import { forwardRef } from "react";
import { Sparkles, Disc, Mic2, Activity } from "lucide-react";

export const ExportCard = forwardRef<HTMLDivElement, { profile: any }>(
  ({ profile }, ref) => {
    return (
      <div
        ref={ref}
        className="w-[1080px] h-[1920px] bg-zinc-950 flex flex-col items-center justify-center p-24 text-white font-sans relative overflow-hidden"
        style={{
          background: "linear-gradient(135deg, #09090b 0%, #1DB954 200%)"
        }}
      >
        {/* Decorative elements */}
        <div className="absolute top-0 right-0 w-[800px] h-[800px] bg-[#1DB954] rounded-full blur-[250px] opacity-20 transform translate-x-1/3 -translate-y-1/3" />
        <div className="absolute bottom-0 left-0 w-[1000px] h-[1000px] bg-[#531db9] rounded-full blur-[300px] opacity-20 transform -translate-x-1/3 translate-y-1/3" />

        <div className="relative z-10 w-full h-full flex flex-col justify-between glass-card bg-black/40 backdrop-blur-3xl rounded-[4rem] border border-white/10 p-20 shadow-2xl">
          
          <header className="flex flex-col items-center text-center space-y-8">
            <div className="bg-[#1DB954]/20 p-8 rounded-full shadow-[0_0_80px_rgba(29,185,84,0.4)]">
              <Sparkles className="w-20 h-20 text-[#1DB954]" />
            </div>
            <h2 className="text-4xl font-bold tracking-widest text-zinc-400 uppercase">My Spotify DNA</h2>
            <div className="space-y-4">
              <p className="text-2xl font-bold tracking-[0.3em] text-[#1DB954] uppercase">Archetype</p>
              <h1 className="text-8xl font-black text-white leading-tight drop-shadow-2xl">
                {profile.archetype}
              </h1>
            </div>
          </header>

          <div className="grid grid-cols-2 gap-12 my-auto py-16">
            <div className="bg-white/5 rounded-3xl p-12 border border-white/10 shadow-xl backdrop-blur-md">
              <h3 className="text-3xl font-bold mb-8 flex items-center gap-4 text-zinc-300">
                <Mic2 className="text-[#1DB954] w-8 h-8"/> Top Artists
              </h3>
              <ol className="space-y-6 text-3xl">
                {profile.topArtists.slice(0, 5).map((a: string, i: number) => (
                  <li key={a} className="flex gap-6 items-center">
                    <span className="font-bold text-zinc-500 w-8">{i + 1}</span>
                    <span className="font-bold text-white">{a}</span>
                  </li>
                ))}
              </ol>
            </div>

            <div className="bg-white/5 rounded-3xl p-12 border border-white/10 shadow-xl backdrop-blur-md">
              <h3 className="text-3xl font-bold mb-8 flex items-center gap-4 text-zinc-300">
                <Disc className="text-[#1DB954] w-8 h-8"/> Top Genres
              </h3>
              <ul className="space-y-6 text-3xl">
                {profile.topGenres.slice(0, 5).map((g: any) => (
                  <li key={g.genre} className="flex justify-between items-center border-b border-white/5 pb-4">
                    <span className="capitalize font-bold text-zinc-200">{g.genre}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <footer className="text-center space-y-6">
            <p className="text-4xl font-medium text-zinc-400">
              Generated by <span className="text-white font-bold">Spotify Personality Profile</span>
            </p>
            <div className="w-32 h-2 bg-[#1DB954] mx-auto rounded-full" />
          </footer>
        </div>
      </div>
    );
  }
);

ExportCard.displayName = "ExportCard";
